### ISSUE TITLE
Rubric Checklist

### ISSUE THREAD

**Issue by dankim444** [dankim444/phillow#5]
# Technical Quality (40 pts)
## Query Complexity (20 pts)
*Please note that a failure to include one of the first four elements may be compensated by an extensive use of another element under the discretion of the grader.*
- [x] Multiple joins (5 pts)
- [x] Subqueries or views (5 pts) 
- [x] Aggregation (5 pts) 
- [x] Universal/Existential checks (5 pts) 
- [x] Non-trivial runtimes (5 pts) 
  - - [x] ~15s for at least 2 queries pre-optimization, ~1s post-optimization 

## Pre-processing (5 pts) 
- [x] Removed incorrect and null values based on purpose (2 pts) 
- [x] Sufficient data cleaning (1 pt) 
- [x] Accurate entity resolution (2 pts) 

## Schema Normalization (10 pts) 
- [x] Correct ER Diagram schema (5 pts) 
- [x] 3NF or BCNF proved (5 pts) 

## Application Robustness (5 pts) 
- [x] Input Sanity (check incorrect inputs, null inputs) (1 pt) 
- [x] No application-breaking bugs (1 pt) 
- [x] Features/queries work for various different user inputs (1 pt) 
- [x] Correct/no malformed rendering for UI elements (2 pts) 

# Scope (15 pts) 
## Queries (10 pts) 
- [x] ≥ 6 small queries (6 pts) 
- [x] ≥ 4 big (i.e. complex) queries drawing on multiple datasets (4 pts) 

## Pages/Features (5 pts) 
- [x] Features should make sense, relate with the theme of the app (2.5 pts) 
- [x] Multiple pages that interact with the database (2.5 pts) 

# Optimization (15 pts) 
## Timings (5 pts) 
- [x] Table with pre- and post-optimization timings of all complex queries 

## Optimizations (10 pts) 
*For each of the following optimization techniques, please explain how it was used. If it was not used, please explain why.*
- [x] Caching (2.5 pts) 
- [x] Indexing (2.5 pts) 
- [x] Re-structuring query (2.5 pts) 
- [x] Clear explanation/justification of optimizations (if no optimization is possible explain why) (2.5 pts) 

# Clarity/Effectiveness of Presentation (i.e., live demo) and Report (10 pts) 
## Presentation (5 pts) 
- [x] Clear explanations (1 pt) 
- [x] Engaging slides (1 pt) 
- [x] Effective use of graphics (1 pt) 
- [x] Accurate content (1 pt) 
- [x] Audible/clear speech (1 pt) 

## Project Report (5 pts) 
- [x] Clear and concise language (1 pt) 
- [x] Effective use of graphics/visualizations (1 pt) 
- [x] Proper grammar/usage (1 pt) 
- [x] Accurate and consistent content (2 pts) 

# Video Recording (5 pts) 
- [x] Concise and good quality (2 pts) 
- [x] Covers core functionalities (3 pts) 

# Look and Feel (5 pts) 
- [x] UI looks different from HW2 UI provided (2.5 pts) 
- [x] Clean and easy to use interface (2.5 pts) 

# Code Quality (5 pts) 
- [x] Clear and organized folder structure (1 pt) 
- [x] Used multiple filed for different components / routes / configurations / apis (2 pts) 
- [x] Comments and documentation (2 pts) 

# Extra Credit (Max 4 pts)
- [x] Code coverage (unit testing >80% for backend and/or >80% frontend (2 pts)
- [x] Deployment (need to have the website deployed so TAs can access during presentation) (2 pts)
